const webPush = require('web-push');
const vapidKeys = webPush.generateVAPIDKeys();
console.log('=================================');
console.log('VAPID KEYS FOR YOUR APP');
console.log('=================================');
console.log('');
console.log('PUBLIC KEY:');
console.log(vapidKeys.publicKey);
console.log('');
console.log('PRIVATE KEY:');
console.log(vapidKeys.privateKey);
console.log('');
console.log('=================================');
console.log('Add these to your .env file:');
console.log(`VAPID_PUBLIC_KEY=${vapidKeys.publicKey}`);
console.log(`VAPID_PRIVATE_KEY=${vapidKeys.privateKey}`);
console.log('VAPID_SUBJECT=mailto:your-email@example.com');
